config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  
  root to: 'evaluations#index', only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord

  ## Validations
  validates :grid, presence: true

  ## Callbacks
  after_create :evaluate_continuous_path

  private

  ## Evaluates a grid after its creation 
  ##  TODO => Could use active-job for background process
  def evaluate_continuous_path

    cp_instance = ::Builder.build(ContinuousPath)

    self.evaluated = true
    self.path_presence, self.path = cp_instance.find_min_path_with_coordinates self.grid
  
    self.save()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: %i[ show edit ]

  # GET /evaluations
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # POST /evaluations
  def create
    @evaluation = Evaluation.new(parsed_params)
    
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to evaluation_url(@evaluation), notice: "Evaluation was successfully created." }        
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evaluation
    @evaluation = Evaluation.find(params[:id])
  end

  def parsed_params
    { grid: JSON.parse(evaluation_params['grid']) }
  end

  # Only allow a list of trusted parameters through.
  def evaluation_params
    params.require(:evaluation).permit(:grid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
  
  ## Gral Grid Info
  def grid_info(grid)
    "Grid of #{grid.size} by #{grid.first.size}"
  end

  ## Hightlights cells that are part of the path
  def highlight_path_cell(row_index, col_index, path)
  
    return '' if path.empty?
    return '' if path.exclude? [row_index, col_index]

    return 'background-color: red;'
  end
end

app/views/evaluations/_form.html.erb
<%= form_with(model: evaluation) do |form| %>
  <% if evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>
      <ul>
        <% evaluation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :grid %>
    <div id="grid"></div>    
    <br>
    <button id="addRowBtn" onclick="addRow();return false;">Add Row</button>
    <button id="addColumnBtn" onclick="addColumn();return false;">Add Column</button>
    <button id="randomBtn" onclick="randomize();return false;">Randomize</button>
    <hr>
    <%= form.hidden_field :grid %>
  </div>
  <br>
  <div class="actions">
    <button id="validateAndSubmitBtn" onclick="validateAndSubmit();">Submit</button>
  </div>
<% end %>

<script>
 
  const grid  = document.getElementById("grid");
  let rows    = 0;
  let columns = 1;
  
  // Function to generate the grid
  function generateGrid() {

    let html = "<table>";

      for (let i = 0; i < rows; i++) {
      html += "<tr>";
      for (let j = 0; j < columns; j++) {
        html += `<td><input type="text" pattern="1|0" maxlength="1" size="1" id="cell-${i}-${j}" required></td>`;
      }
      html += "</tr>";
    }

    html += "</table>";
    grid.innerHTML = html;
  }

  // Function to add rows
  function addRow() {
    rows++;
    generateGrid();
    return false;
  }

  // Function to add columns
  function addColumn() {
    columns++;
    generateGrid();
    return false;
  }

  // Randomize generation
  function randomize() {

    rows    = Math.floor(Math.random() * 10) + 2;
    columns = Math.floor(Math.random() * 10) + 2;

    generateGrid();
    fillGrid();
  }

  // Fill generated grid 
  function fillGrid() {

    for (let i = 0; i < rows; i++) {
      for (let j = 0; j < columns; j++) {

        document.getElementById(`cell-${i}-${j}`).value = Math.random()<0.5?0:1
      }
    }
  }

  // Validates and submits
  function validateAndSubmit() {

    let gridx = [];

    for (let i = 0; i < rows; i++) {
      
      let cols = [];
      
      for (let j = 0; j < columns; j++) {

        let value = document.getElementById(`cell-${i}-${j}`).value;

        if ( value!='0' &&  value!='1' ) {

          alert('Some of the values on the grid are invalid');
          return false;
        }

        cols.push(value);
      }
      gridx.push(cols);
    }

    document.getElementById('evaluation_grid').value = JSON.stringify(gridx);
    document.getElementsByTagName('form')[0].submit();    
  }
</script>

app/views/evaluations/_grid_path.html.erb
<table>
  <% evaluation.grid.each_with_index do |row, row_index| %>  
      <tr>
        <% row.each_with_index do |col, col_index| %>
          <td style="<%=highlight_path_cell(row_index, col_index, evaluation.path)%>"><%=col%></td>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluations</h1>

<table>
  <thead>
    <tr>
      <th style="text-align: left; ">Grid</th>
      <th>Evaluated?</th>
      <th>Conductive Path Presence?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= grid_info(evaluation.grid) %></td>
        <td><%= evaluation.evaluated %></td>
        <td><%= evaluation.path_presence %></td>
        <td><%= link_to 'Show', evaluation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grid Info:</strong>
  <%= grid_info(@evaluation.grid) %>
</p>

<p>
  <strong>Continuous Path Presence:</strong>
  <%= @evaluation.path_presence %>
</p>

<p>
  <strong>Grid:</strong>
  <%= render 'grid_path', evaluation: @evaluation %>
</p>

<%= link_to 'Back', evaluations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Continuous conductive path</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>